# Tomcat Server Port
server:
  port: 8080

# Spring Config
spring:

  # OAuth2
  security:
    oauth2:
      client:
        registration:
          facebook: #facebook 是 registration 屬性的唯一 ID
            client-id: 2752511384784452
            client-secret: cd52044ad75e1bc0903c38f55ddcea12
            accessTokenUri: https://graph.facebook.com/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            resource:
              userInfoUri: https://graph.facebook.com/me

          github: #github 是 registration 屬性的唯一 ID
            client-id: 7eec64ece4a92727f2a9
            client-secret: 59a88e42db12717a9cb5aa3e51ba8945ca50e14f

  # Devtool
  devtools:
    restart:
      enabled: true
